### PR TITLE
Update electron

### PR DESCRIPTION
**Pull request by mimi89999**

### CODE REVIEW

**Comment by EragonJ** [comment]
why ?

**Comment by mimi89999** [comment]
Since we are testing kaku with the latest version of electron (npm install electron-prebuilt -g) we could also build kaku with the latest version of electron...

**Comment by EragonJ** [comment]
If so, I think we should lock down the version and make sure we use the same version to test / build. Otherwise, this would be insane if error logs are coming from newer version of electron while the others are using the old one.

By doing so, we don't have to keep updating the version number until we want to fit any stabled Electron.

**Comment by EragonJ** [comment]
Okay, from now on, let's lock down the version of electron.

**Pull request merged**
