### PR TITLE
Audius.co search integration

### PR DESCRIPTION
**Pull request by brycedev**
Added track search support using the Audius.co searcher. 

What got changed here :
* Modified kaku-core to include Audius.co support.

### CODE REVIEW

**Comment by EragonJ** [comment]
@brycedev can u check why the build is failed ? I tried to rebuild and see how's going already.

**Comment by brycedev** [comment]
Yes, I will look into this.

**Comment by EragonJ** [comment]
@brycedev anything good? Need help (?)

**Comment by EragonJ** [comment]
nvm i can check it later. thanks for the help

**Comment by brycedev** [comment]
Hello! I looked into the build error. It looks like your CI may not be able to connect to Github via SSH, so it terminates the build : 

`The authenticity of host 'github.com (140.82.114.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated`

**Comment by EragonJ** [comment]
@brycedev cool thanks! I'll take a look :)

**Pull request merged**
