### PR TITLE
Revert "rewrite with ES6 syntax"

### PR DESCRIPTION
**Pull request by neighborhood999**
Reverts EragonJ/Kaku#488

### CODE REVIEW

**Comment by funilrys** [comment]
Question why was it merged ? + Why do you revert it ?

**Comment by neighborhood999** [comment]
@funilrys Sorry, I think this refactor have something problem, I will push new PR.

**Comment by funilrys** [comment]
Okay clear :) Next time test it twice :wink: :smile_cat:

**Comment by neighborhood999** [comment]
Sorry, my bad.

**Comment by funilrys** [comment]
No problem @neighborhood999 that's can happen we're not robot :wink: !!

**Comment by EragonJ** [comment]
@neighborhood999 +++ at least you made a good try :P

**Pull request merged**
