### PR TITLE
Update to es6 syntax

### PR DESCRIPTION
**Pull request by neighborhood999**

### CODE REVIEW

**Comment by EragonJ** [comment]
@neighborhood999 I am focusing on releasing 1.8.0, so this patch will be postponed a little bit because every change may cause regression issues, just a headsup to let you know about current status :)

**Comment by neighborhood999** [comment]
@EragonJ Okay!

**Comment by EragonJ** [comment]
@neighborhood999 there are so many errors in this patch, can you help to check it ? 

There are two things that you may need to check

1. `this` scope
2. `this.state`

**Comment by neighborhood999** [comment]
I think I need one by one update this file and commit it, so I close this PR.

**Pull request closed without merging**
