### PR TITLE
update react version

### PR DESCRIPTION
**Pull request by neighborhood999**
issue #379 

I try to update react version, react current version is `15.0.1`
but some package doesn't support now, so I use `0.14.8` version
until related package update and we will update to new version. :smile:

### CODE REVIEW

**Comment by EragonJ** [comment]
thanks @neighborhood999 ! I prefer to postpone this PR to next milestone because this would be a breaking change.

**Comment by neighborhood999** [comment]
@EragonJ That's OK！thank you

**Comment by EragonJ** [comment]
@neighborhood999 can you play around this patch again ? Because 1.7.0 just got released, I think we can try to upgrade things now :) Just need to make sure functionalities all work well before doing the merge.

**Comment by neighborhood999** [comment]
@EragonJ done！

**Comment by EragonJ** [comment]
Thanks @neighborhood999  !

**Pull request merged**
