### PR TITLE
Polish translation 

### PR DESCRIPTION
**Pull request by mimi89999**

### CODE REVIEW

**Comment by EragonJ** [comment]
@mimi89999, are you native speaker of Polish & French ?

**Comment by EragonJ** [comment]
Just want to make sure these translations do make sense to native users.

**Comment by EragonJ** [comment]
And also, can you squeeze commits into one ? You can check my receding to know what to do this, thanks ! https://asciinema.org/a/11269

**Comment by mimi89999** [comment]
What commits shall I squeeze?

**Comment by mimi89999** [comment]
@EragonJ I'm a native speaker of both...

**Comment by EragonJ** [comment]
For the moment, if we add too many languages translations would create more workloads on me because right now I want to focus more on functionalities instead of translations. With zh_tw & en, I can make sure L10nManager and its related codes are workable.

I really appreciate the contribution, but I am keen to put these works on second stage before Kaku is mature enough. Any idea ?

**Comment by EragonJ** [comment]
Hi @mimi89999 , I think Kaku is stable enough to add Polish & French translation, are you able to update your PRs ? And can you help to squeeze them into one commit ? thanks !

**Comment by EragonJ** [comment]
And by the way, right now you should be able to build for different platform (take your's env for example, that would be linux), so feel free to give it a check

**Comment by EragonJ** [comment]
@mimi89999 feel free to update this patch and rebase to latest master to make it mergable

**Comment by EragonJ** [comment]
@mimi89999 , are you still working on this ? I am going to close this PR right now and feel free to re-open and if you did update your patch, thanks.

**Pull request closed without merging**
